export type SystemId = 'skeletal'|'muscular'|'arterial'|'venous'|'nervous'|'digestive'|'respiratory'|'urinary'|'reproductive'|'lymphatic'|'endocrine'|'integumentary'|'connective'|'sensory'|'cardiac';
export const SYSTEMS: {id:SystemId;name:string;nameVi:string;color:string;description:string;descriptionVi:string}[] = [
 {id:'skeletal',name:'Skeleton',nameVi:'Xương',color:'#e2d9ba',description:'Bones form the supporting framework of the body, protect organs, and provide attachment points for muscles. Their internal tissue also stores minerals and produces blood cells.',descriptionVi:'Xương tạo khung nâng đỡ cơ thể, bảo vệ nội tạng và là điểm bám của cơ. Mô bên trong xương còn dự trữ khoáng chất và sinh huyết cầu.'},
 {id:'muscular',name:'Muscles',nameVi:'Cơ',color:'#a85b50',description:'Skeletal muscles generate movement by pulling on their attachments. Together with tendons, they move joints, stabilize posture, and produce heat.',descriptionVi:'Cơ vân tạo chuyển động bằng cách co kéo các điểm bám. Cùng với gân, chúng vận hành khớp, giữ tư thế và sinh nhiệt.'},
 {id:'cardiac',name:'Heart',nameVi:'Tim',color:'#b96760',description:'The heart is a muscular pump with four chambers. Its valves direct blood forward through the pulmonary and systemic circuits.',descriptionVi:'Tim là một bơm cơ có bốn buồng. Các van tim điều hướng dòng máu đi qua vòng tuần hoàn phổi và vòng tuần hoàn hệ thống.'},
 {id:'sensory',name:'Sensory organs',nameVi:'Giác quan',color:'#b0c8ce',description:'These structures contribute to special senses, including sight, hearing, and balance. Their specialized tissues detect stimuli and work with the nervous system to convey information.',descriptionVi:'Các cấu trúc này đóng góp vào các giác quan đặc biệt như thị giác, thính giác và thăng bằng. Mô chuyên biệt của chúng tiếp nhận kích thích và phối hợp với hệ thần kinh để truyền thông tin.'},
 {id:'arterial',name:'Arteries',nameVi:'Động mạch',color:'#c05245',description:'The heart drives blood through the circulation. Arteries carry blood away from the heart to supply tissues or, in the pulmonary circuit, to the lungs.',descriptionVi:'Tim bơm máu đi khắp cơ thể qua hệ tuần hoàn. Động mạch mang máu rời khỏi tim để nuôi các mô, hoặc trong vòng tuần hoàn phổi, đến phổi.'},
 {id:'venous',name:'Veins',nameVi:'Tĩnh mạch',color:'#527c9f',description:'Veins return blood toward the heart. Superficial and deep networks collect blood from the tissues; the pulmonary veins bring oxygenated blood back from the lungs.',descriptionVi:'Tĩnh mạch đưa máu trở về tim. Hệ tĩnh mạch nông và sâu thu gom máu từ các mô; tĩnh mạch phổi đưa máu đã trao đổi oxy trở về từ phổi.'},
 {id:'nervous',name:'Nervous system',nameVi:'Thần kinh',color:'#d8b565',description:'The brain, spinal cord, and peripheral nerves carry and process signals. They support sensation, movement, coordination, and automatic regulation of body functions.',descriptionVi:'Não, tủy sống và các dây thần kinh ngoại biên truyền dẫn và xử lý tín hiệu. Chúng hỗ trợ cảm giác, vận động, phối hợp và điều hòa tự động các chức năng cơ thể.'},
 {id:'respiratory',name:'Respiratory',nameVi:'Hô hấp',color:'#b98991',description:'The airways conduct air to the lungs, where oxygen and carbon dioxide move between air and blood. Breathing depends on pressure changes produced by respiratory muscles.',descriptionVi:'Đường thở dẫn khí vào phổi, nơi oxy và carbon dioxide trao đổi giữa khí và máu. Hô hấp phụ thuộc vào sự thay đổi áp suất do các cơ hô hấp tạo ra.'},
 {id:'digestive',name:'Digestive',nameVi:'Tiêu hóa',color:'#b8916b',description:'The digestive tract breaks down food, absorbs nutrients and water, and moves waste onward. Accessory organs contribute bile and digestive enzymes.',descriptionVi:'Ống tiêu hóa phân giải thức ăn, hấp thu dưỡng chất và nước, rồi đẩy chất thải đi tiếp. Các cơ quan phụ trợ cung cấp mật và enzyme tiêu hóa.'},
 {id:'urinary',name:'Urinary',nameVi:'Tiết niệu',color:'#b47961',description:'The kidneys filter blood and regulate fluid, electrolyte, and acid–base balance. Urine travels through the ureters to the bladder and exits through the urethra.',descriptionVi:'Thận lọc máu và điều hòa cân bằng dịch, điện giải, acid–base. Nước tiểu di chuyển qua niệu quản tới bàng quang rồi thoát ra qua niệu đạo.'},
 {id:'lymphatic',name:'Lymphatic',nameVi:'Bạch huyết',color:'#879f7c',description:'Lymphatic vessels return excess tissue fluid to the circulation. Lymph nodes and other lymphoid organs support immune surveillance and responses.',descriptionVi:'Mạch bạch huyết đưa dịch mô dư thừa trở về hệ tuần hoàn. Hạch bạch huyết và các cơ quan bạch huyết khác hỗ trợ giám sát và đáp ứng miễn dịch.'},
 {id:'endocrine',name:'Endocrine',nameVi:'Nội tiết',color:'#c5a09a',description:'Endocrine organs release hormones into the blood to coordinate processes such as metabolism, growth, stress responses, and reproduction.',descriptionVi:'Các cơ quan nội tiết tiết hormone vào máu để điều phối các quá trình như chuyển hóa, tăng trưởng, đáp ứng stress và sinh sản.'},
 {id:'reproductive',name:'Reproductive',nameVi:'Sinh sản',color:'#bda098',description:'The male reproductive structures represented here contribute to sperm production, maturation, transport, and the production of sex hormones.',descriptionVi:'Các cấu trúc sinh sản nam được thể hiện ở đây góp phần sản xuất, trưởng thành, vận chuyển tinh trùng và sản xuất hormone sinh dục.'},
 {id:'integumentary',name:'Body surface',nameVi:'Bề mặt cơ thể',color:'#ba9b7d',description:'The body surface provides an outer anatomical reference. The integumentary system forms a protective barrier and contributes to sensation and temperature regulation.',descriptionVi:'Bề mặt cơ thể cung cấp mốc giải phẫu bên ngoài. Hệ này tạo lớp bảo vệ và góp phần vào cảm giác, điều hòa thân nhiệt.'},
 {id:'connective',name:'Connective tissue',nameVi:'Mô liên kết',color:'#aec3bb',description:'Cartilage, ligaments, and other connective tissues support, connect, and separate structures. Their roles include stabilizing joints and distributing mechanical loads.',descriptionVi:'Sụn, dây chằng và các mô liên kết khác nâng đỡ, kết nối và ngăn cách các cấu trúc. Vai trò gồm ổn định khớp và phân tán tải trọng cơ học.'},
];
export interface Part {id:string;name:string;conceptId:string;system:SystemId;chunk:number;positions:number;normals:number;indices:number;vertexCount:number;indexCount:number;bounds:[number[],number[]]}
export interface Concept {id:string;name:string;elements:string[]}
export interface Atlas {version:string;sex?:'male';source?:string;scope?:string;parts:Part[];concepts:Concept[];chunks:{url:string;bytes:number;gzip?:string;gzipBytes?:number}[];triangles:number}
export type View = 'three-quarter'|'front'|'back'|'side';
export interface SceneState {inspectorOpen?:boolean;explode:number;visible:SystemId[];selected:string[];isolate:boolean;view:View;rotate:boolean;reset:number}
export const DEFAULT_VISIBLE:SystemId[] = ['muscular'];
export const EXPLANATIONS:Record<string,string> = {
 'heart':'A muscular pump in the chest. Its right side sends blood to the lungs; its left side sends blood through the systemic circulation.',
 'liver':'A large organ beneath the right side of the diaphragm. It processes absorbed nutrients, produces bile, and synthesizes many proteins carried in the blood.',
 'brain':'The central organ of the nervous system. Its interconnected regions support perception, movement, memory, language, and the regulation of bodily functions.',
 'stomach':'A muscular chamber between the esophagus and small intestine. It stores and mixes food with acid and enzymes before releasing it into the duodenum.',
 'spleen':'A lymphoid organ in the upper left abdomen. It filters blood, removes aging blood cells, and participates in immune responses.',
 'pancreas':'An abdominal organ with digestive and endocrine roles. It supplies enzymes to the small intestine and releases hormones including insulin and glucagon.',
 'urinary bladder':'A muscular reservoir in the pelvis that stores urine arriving from the kidneys through the ureters.',
 'trachea':'The main airway connecting the larynx to the bronchi. Its cartilage supports keep the airway open during breathing.',
 'diaphragm':'A broad muscle separating the chest and abdomen. When it contracts, it increases chest volume and helps draw air into the lungs.',
};
export function explanation(name:string,system:SystemId,lang:'en'|'vi'='en'){
 const curated=EXPLANATIONS[name.toLowerCase()];
 if(curated)return curated;
 const sys=SYSTEMS.find(s=>s.id===system);
 return (lang==='vi'?sys?.descriptionVi:sys?.description) ?? '';
}
